#indent_style = "Block" # Block | Visual
#use_small_heuristics = "Default" # Default | Off | Max
#binop_separator = "Front" # Front | Back
#combine_control_expr = true
#comment_width = 80
condense_wildcard_suffixes = true
#control_brace_style = "AlwaysSameLine" # AlwaysNextLine | AlwaysSameLine | ClosingNextLine
#disable_all_formatting = false
#error_on_line_overflow = false
#error_on_unformatted = false
#fn_args_density = "Tall" # Tall | Compressed | Vertical
#brace_style = "SameLineWhere" # AlwaysNextLine | PreferSameLine | SameLineWhere
#empty_item_single_line = true
#enum_discrim_align_threshold = 0
#fn_single_line = false
#where_single_line = false
#force_explicit_abi = true
#format_strings = false
#format_macro_matchers = false
#format_macro_bodies = true
#hard_tabs = false
#imports_indent = "Block" # Block | Visual
#imports_layout = "Mixed" # Horizontal | HorizontalVertical | Mixed | Vertical
merge_imports = true
#match_block_trailing_comma = false
#max_width = 100
#merge_derives = true
#force_multiline_blocks = false
#newline_style = "Auto" # Auto | Native | Unix | Windows
normalize_comments = true
#remove_nested_parens = true
#reorder_imports = true
#reorder_modules = true
reorder_impl_items = true
report_todo = "Unnumbered" # Always | Unnumbered | Never
report_fixme = "Unnumbered" # Always | Unnumbered | Never
#skip_children = false
#space_after_colon = true
#space_before_colon = false
#struct_field_align_threshold = 0
#spaces_around_ranges = false
#struct_lit_single_line = true
#tab_spaces = 4
#trailing_comma = "Vertical" # Always | Never | Vertical
#trailing_semicolon = true
#type_punctuation_density = "Wide" # Compressed | Wide
use_field_init_shorthand = true
use_try_shorthand = true
#format_doc_comments = true
wrap_comments = true
#match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
#required_version = "1.0.0"
#hide_parse_errors = false
color = "Auto" # Auto | Always | Never
unstable_features = true
#license_template_path = ""
#ignore = []
edition = "2018" # 2015 | 2018
#version = "One" # One | Two
normalize_doc_attributes = true
